#!/usr/bin/env bash

function _keybase() {
    local cur prev prevs lprev
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    prevs=("${COMP_WORDS[@]:1:$COMP_CWORD-1}")
    lprev=${#prevs[@]}

    # Will try to keep args and their cases sorted alphabetically -jhazelwo
    local commands="base62 chat cert config ctl currency decrypt deprovision device dump-keyfamily encrypt follow help id list-followers list-following log login logout paperkey passphrase pgp ping prove rekey search sign signup sigs status team track unfollow unlock untrack update verify version"

    if [[ $lprev -eq 0 ]]; then
        COMPREPLY+=($(compgen -W "${commands}" -- ${cur}))
    else
        case "${prevs[0]}" in
            base62)
                commands="decode encode"
                if [[ $lprev -eq 1 ]]; then
                    COMPREPLY+=($(compgen -W "${commands} help" -- ${cur}))
                    return 0
                else
                    case "${prevs[1]}" in
                        help)
                            if [[ $lprev -eq 2 ]]; then
                                COMPREPLY+=($(compgen -W "${commands}" -- ${cur}))
                                return 0
                            fi
                            ;;
                    esac
                    return 0
                fi
                ;;
            chat)
                commands="api delete-channel delete-history download hide join-channel leave-channel rename-channel create-channel list list-channels list-members list-unread mute read readd-member report retention-policy search send upload"
                if [[ $lprev -eq 1 ]]; then
                    COMPREPLY+=($(compgen -W "${commands} help" -- ${cur}))
                    return 0
                else
                    case "${prevs[1]}" in
                        help)
                            if [[ $lprev -eq 2 ]]; then
                                COMPREPLY+=($(compgen -W "${commands}" -- ${cur}))
                                return 0
                            fi
                            ;;
                    esac
                    return 0
                fi
                ;;
            cert)
                return 0
                ;;
            config)
                commands="get set info"
                if [[ $lprev -eq 1 ]]; then
                    COMPREPLY+=($(compgen -W "${commands} help" -- ${cur}))
                    return 0
                else
                    case "${prevs[1]}" in
                        help)
                            if [[ $lprev -eq 2 ]]; then
                                COMPREPLY+=($(compgen -W "${commands}" -- ${cur}))
                                return 0
                            fi
                            ;;
                    esac
                    return 0
                fi
                ;;
            ctl)
                commands="app-exit log-rotate reload restart start stop watchdog watchdog2"
                if [[ $lprev -eq 1 ]]; then
                    COMPREPLY+=($(compgen -W "${commands} help" -- ${cur}))
                    return 0
                else
                    case "${prevs[1]}" in
                        help)
                            if [[ $lprev -eq 2 ]]; then
                                COMPREPLY+=($(compgen -W "${commands}" -- ${cur}))
                                return 0
                            fi
                            ;;
                    esac
                    return 0
                fi
                ;;
            currency)
                commands="add"
                if [[ $lprev -eq 1 ]]; then
                    COMPREPLY+=($(compgen -W "${commands} help" -- ${cur}))
                    return 0
                else
                    case "${prevs[1]}" in
                        help)
                            if [[ $lprev -eq 2 ]]; then
                                COMPREPLY+=($(compgen -W "${commands}" -- ${cur}))
                                return 0
                            fi
                            ;;
                    esac
                    return 0
                fi
                ;;
            decrypt)
                return 0
                ;;
            deprovision)
                return 0
                ;;
            device)
                commands="remove list add"
                if [[ $lprev -eq 1 ]]; then
                    COMPREPLY+=($(compgen -W "${commands} help" -- ${cur}))
                    return 0
                else
                    case "${prevs[1]}" in
                        help)
                            if [[ $lprev -eq 2 ]]; then
                                COMPREPLY+=($(compgen -W "${commands}" -- ${cur}))
                                return 0
                            fi
                            ;;
                    esac
                    return 0
                fi
                ;;
            dump-keyfamily)
                return 0
                ;;
            encrypt)
                return 0
                ;;
            follow)
                return 0
                ;;
            help)
                commands="$commands advanced gpg keyring tor"
                if [[ $lprev -eq 1 ]]; then
                    COMPREPLY+=($(compgen -W "${commands} help" -- ${cur}))
                    return 0
                fi
                ;;
            id)
                return 0
                ;;
            list-followers)
                return 0
                ;;
            list-following)
                return 0
                ;;
            log)
                commands="send"
                if [[ $lprev -eq 1 ]]; then
                    COMPREPLY+=($(compgen -W "${commands} help" -- ${cur}))
                    return 0
                else
                    case "${prevs[1]}" in
                        help)
                            if [[ $lprev -eq 2 ]]; then
                                COMPREPLY+=($(compgen -W "${commands}" -- ${cur}))
                                return 0
                            fi
                            ;;
                    esac
                    return 0
                fi
                ;;
            login)
                return 0
                ;;
            logout)
                return 0
                ;;
            paperkey)
                return 0
                ;;
            passphrase)
                commands="change recover"
                if [[ $lprev -eq 1 ]]; then
                    COMPREPLY+=($(compgen -W "${commands} help" -- ${cur}))
                    return 0
                else
                    case "${prevs[1]}" in
                        help)
                            if [[ $lprev -eq 2 ]]; then
                                COMPREPLY+=($(compgen -W "${commands}" -- ${cur}))
                                return 0
                            fi
                            ;;
                    esac
                    return 0
                fi
                ;;
            pgp)
                commands="gen pull update select sign encrypt decrypt verify export import drop list purge"
                if [[ $lprev -eq 1 ]]; then
                    COMPREPLY+=($(compgen -W "${commands} help" -- ${cur}))
                    return 0
                else
                    case "${prevs[1]}" in
                        help)
                            if [[ $lprev -eq 2 ]]; then
                                COMPREPLY+=($(compgen -W "${commands}" -- ${cur}))
                                return 0
                            fi
                            ;;
                    esac
                    return 0
                fi
                ;;
            ping)
                return 0
                ;;
            prove)
                if [[ $lprev -eq 1 ]]; then
                    local services="coinbase facebook github hackernews reddit twitter web https dns http"
                    COMPREPLY+=($(compgen -W "${services}" -- ${cur}))
                    return 0
                fi
                ;;
            rekey)
                commands="status paper"
                if [[ $lprev -eq 1 ]]; then
                    COMPREPLY+=($(compgen -W "${commands} help" -- ${cur}))
                    return 0
                else
                    case "${prevs[1]}" in
                        help)
                            if [[ $lprev -eq 2 ]]; then
                                COMPREPLY+=($(compgen -W "${commands}" -- ${cur}))
                                return 0
                            fi
                            ;;
                    esac
                    return 0
                fi
                ;;
            search)
                return 0
                ;;
            sign)
                return 0
                ;;
            signup)
                return 0
                ;;
            sigs)
                commands="list revoke"
                if [[ $lprev -eq 1 ]]; then
                    COMPREPLY+=($(compgen -W "${commands} help" -- ${cur}))
                    return 0
                else
                    case "${prevs[1]}" in
                        help)
                            if [[ $lprev -eq 2 ]]; then
                                COMPREPLY+=($(compgen -W "${commands}" -- ${cur}))
                                return 0
                            fi
                            ;;
                    esac
                    return 0
                fi
                ;;
            status)
                return 0
                ;;
            team)
                commands="create add-member remove-member edit-member list-memberships list-members show-tree rename request-access list-requests ignore-request accept-invite leave delete api settings profile-load"
                if [[ $lprev -eq 1 ]]; then
                    COMPREPLY+=($(compgen -W "${commands} help" -- ${cur}))
                    return 0
                else
                    case "${prevs[1]}" in
                        help)
                            if [[ $lprev -eq 2 ]]; then
                                COMPREPLY+=($(compgen -W "${commands}" -- ${cur}))
                                return 0
                            fi
                            ;;
                    esac
                    return 0
                fi
                ;;
            track)
                return 0
                ;;
            unfollow)
                return 0
                ;;
            unlock)
                return 0
                ;;
            untrack)
                return 0
                ;;
            update)
                commands="check run check-in-use notify"
                if [[ $lprev -eq 1 ]]; then
                    COMPREPLY+=($(compgen -W "${commands} help" -- ${cur}))
                    return 0
                else
                    case "${prevs[1]}" in
                        help)
                            if [[ $lprev -eq 2 ]]; then
                                COMPREPLY+=($(compgen -W "${commands}" -- ${cur}))
                                return 0
                            fi
                            ;;
                    esac
                    return 0
                fi
                ;;
            verify)
                return 0
                ;;
            version)
                return 0
                ;;
        esac
    fi
}
complete -F _keybase keybase

# vim: syntax=sh sts=4 ts=4 sw=4 sr et
